name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd /var/www/mean-app

            docker-compose down || true

            docker rm -f mongodb || true

            docker system prune -f || true

            git pull origin main

            docker-compose up -d --build
